public class Constants {
    
    //GigaComm Constants
    public static String TBA = 'TBA';
    public static String AUSTRALIA = 'Australia';
    
    //Generic Constants
    public static final String GENERIC_BLANK = '';
    public static final String GENERIC_SPACE = ' ';
    public static final String GENERIC_SUCCESS = 'success';
    public static final String GENERIC_UPPERCASE_SUCCESS = 'Success';
    public static final String GENERIC_ERROR = 'error';
    public static final String GENERIC_UPPERCASE_ERROR = 'Error';
    public static final String GENERIC_COMMA = ',';
    public static final String GENERIC_NEXT_LINE = '\n';
    public static final String GENERIC_PERIOD = '.';
    public static final String GENERIC_EQUALS = '=';
    public static final String GENERIC_QUESTION_MARK = '?';
    
    //Date and Time Constants
    public static final String DATE_AND_TIME_TIME_EXTENSION = '00:00:00';
    
    //SObject Field Constants
    public static final String SOBJECT_FIELD_ID = 'Id';
    
    //SObject Constants
    public static final String SOBJECT_ACCOUNT = 'Account';
    public static final String SOBJECT_OPPORTUNITY = 'Opportunity';
    public static final String SOBJECT_OPPORTUNITY_LINE_ITEM = 'OpportunityLineItem';
    
    //Opportunity Constants
    public static final String OPPORTUNITY_STAGE_PROSPECTING = 'Prospecting';
    
    //Exception Log Constants
    public static final Integer EXCEPTION_LOG_STACK_TRACE_FIELD_LIMIT = 255;
    public static final Integer EXCEPTION_LOG_EXCEPTION_LOG_FIELD_LIMIT = 131072;
    
    //Regular Expressions
    public static final String REGEX_PERIOD = '\\.';
    
    //Integration Constants
    public static final String INTEGRATION_REST_METHOD_GET = 'GET';
    public static final String INTEGRATION_REST_METHOD_POST = 'POST';
    public static final String INTEGRATION_REST_METHOD_PUT = 'PUT';
    public static final Integer INTEGRATION_REST_RESPONSE_200 = 200;
    public static final Integer INTEGRATION_REST_RESPONSE_401 = 401;
    public static final Integer INTEGRATION_REST_RESPONSE_400 = 400;
    
    //URI=L Constants
    public static final String URL_ENCODE_DOUBLE_QUOTE = '%22';
     
    public static final String INTEGRATION_KEY_TYPE = 'Type';
    public static final String INTEGRATION_KEY_TYPE_X = 'Type_x';
    public static final String INTEGRATION_KEY_DATE = 'Date';
    public static final String INTEGRATION_KEY_DATE_X = 'Date_x';
    public static final String INTEGRATION_VALUE_CONTENT_TYPE_APPJSON = 'application/json';
    public static final String INTEGRATION_VALUE_CONTENT_TYPE_APPPDF = 'application/pdf';
    public static final String INTEGRATION_KEY_CONTENT_TYPE = 'Content-Type';
    public static final String INTEGRATION_X_API_KEY = 'x-api-key';
    
    
    //Rest Response Collection    
    public static final String INTEGRATION_REST_METHOD_PATCH = 'PATCH';
    public static final String INTEGRATION_AUTHORIZATION = 'Authorization';
    public static final String INTEGRATION_BEARER = 'Bearer ';
    public static final String INTEGRATION_KEY_LOCALE = 'en-US';
    public static final String INTEGRATION_KEY_CONTENT_LANGUAGE = 'Content-Language';
    
    //Error Messages
    public static final String ERROR_REQUEST_NOT_SET = 'Request has not been set.';
    
 	//MEta Collection
    public static final String META_CONVERSIONS_API = 'Meta Conversions API';
    public static final String META_LEAD_CONVERSION = 'Meta Lead Conversion';
    
    
    //Clubs
    public static final String CLUB_BODYFIT_AUBURN = 'Bodyfit Auburn';
    public static final String CLUB_BODYFIT_BLACKTOWN = 'Bodyfit Blacktown';
    public static final String CLUB_BODYFIT_EMERTON = 'Bodyfit Emerton';
    public static final String CLUB_BODYFIT_GLEBE = 'Bodyfit Glebe';
    public static final String CLUB_BODYFIT_MARRICKVILLE = 'Bodyfit Marrickville';
    public static final String CLUB_BODYFIT_MIRANDA = 'Bodyfit Miranda';
    public static final String CLUB_BODYFIT_REDFERN = 'Bodyfit Redfern';
    public static final String CLUB_BODYFIT_SHELLHARBOUR = 'Bodyfit Shellharbour';
    public static final String CLUBFIT_ALL_CLUBS_PROSPECTS_SCHEDULER= 'ClubfitAllClubsProspectsScheduler';
    
    //Clubfit Collection
    
    public static final String INTEGRATION_CLUBFIT_VERSION = '/v1';
    public static final String INTEGRATION_CLUBFIT_PROSPECTS = '/prospects';
    public static final String INTEGRATION_CLUBFIT_TOKEN = '/token';
    public static final String INTEGRATION_CLUBFIT_STATUS = 'status=';
    public static final String INTEGRATION_CLUBFIT_FROM_DATE = 'fromdate=';
    
    
    
 	public static final String CRM = 'crm';
    public static final String SALESFORCE = 'Salesforce';
    public static final String WEBSITE = 'website';
    public static final String CONVERTED = 'All Leads';
    public static final String INTEGRATION_SUBSCRIPTION_KEY = 'en-US';
    public static final String INTEGRATION_META_VERSION = '/v23.0';
    public static final String INTEGRATION_META_EVENTS = '/events?';
    public static final String ACCESS_TOKEN = 'access_token';
    
    
    public static final String PARENT = 'PARENT';    

}